//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSelections
    {
        public int CourseSelectionId { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public Nullable<bool> IsApprovedByAdvisor { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Users Users { get; set; }
    }
}
