//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApiProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextDBEntities : DbContext
    {
        public ContextDBEntities()
            : base("name=ContextDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdvisorAssignments> AdvisorAssignments { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<CourseSelections> CourseSelections { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Terms> Terms { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
